portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('principal.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

principal/urls.py
from django.urls import path

from . import views

app_name = 'principal'

urlpatterns = [
    path(
        '',
        views.PrincipalHome.as_view(),
        name="home"
    ),
    path(
        'projects',
        views.PrincipalProjects.as_view(),
        name="projects"
    )
]

principal/models.py
from django.db import models

# Create your models here.

principal/views.py
from django.views.generic import TemplateView

# Create your views here.


class PrincipalHome(TemplateView):
    template_name = 'principal/pages/home.html'


class PrincipalProjects(TemplateView):
    template_name = 'principal/pages/projects.html'

principal/templates/principal/pages/home.html
{% extends 'global/base.html' %}
{% block content %}
    <div class="home_container">
        <div class="home_gradient">
            {% include 'principal/partials/home_intro.html' %}
            {% include 'principal/partials/about_me.html' %}
            {% include 'principal/partials/panels.html' %}
        </div>
    </div>
{% endblock content %}

principal/templates/principal/pages/projects.html
{% extends 'global/base.html' %}
{% block content %}
    <div class="home_container">
        <div class="home_gradient">
            {% include "principal/partials/projects_top.html" %}
        </div>
    </div>
{% endblock content %}

principal/templates/principal/partials/about_me.html
<div class="about_container">
    <div class="about_panel about_panel_hidden" id="aboutme">
        <div class="about_panel_margin">
            <p>
                Sou um projetista insano e já tenho alguns projetos em progresso e pensando em outros futuramente,
                iniciei com desenvolvimento web mas estou focando em uma programação mais abrangente, como Java, JavaScript, TypeScript e Python.
                Pela minha paixão em técnologia, realizando alguns estudos, descobri que minha preferência era por programação.
                Desde então, tenho estudado algumas linguagens que compõem meus atuais projetos.
            </p>
        </div>
    </div>
</div>

principal/templates/principal/partials/home_intro.html
<div class="intro_container">
    <div class="intro_positioner">
            <div class="intro_text">
                <h2 class="intro_title">
                    Eu sou o SoldadoZuero
                </h2>
            </div>
            <div class="intro_text">
                <h2 class="intro_title">
                    | Um projetista insano,
                    e esse é meu portfolio.
                </h2>
            </div>
    </div>
</div>

principal/templates/principal/partials/intro_home.html
<div class="intro_container">
    <div class="intro_positioner">
            <div class="intro_text">
                <h2 class="intro_title">
                    Eu sou Willy P.
                </h2>
            </div>
            <div class="intro_text">
                <h2 class="intro_title">
                    | Um projetista insano,
                    e esse é meu portfolio.
                </h2>
            </div>
    </div>
</div>

principal/templates/principal/partials/panels.html
<div class="project_container">
    <div class="project_menu_open" id="project_panel">
        <div class="project_panel" id="twitch_desc">
            <img src="/media/Twitch-icon-purple.png" alt="SoldadoZuero Streamer Project">
            <div>
                <i class="fa-solid fa-check"></i><span>Afiliação</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>1000 Seguidores</span>
            </div>
            <div>
                <i class="fa-solid fa-check"></i><span>Servidor do Discord</span>
            </div>
            <div>
                <i class="fa-solid fa-wrench"></i><span>Chatbot</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>Repaginar emotes</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>Trailer do canal</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>Parceria</span>
            </div>
            <a href="https://twitch.tv/soldadozuero" class="project_button button_twitch" rel="noopener noreferrer" target="_blank">
                Me acompanhe 
                <i class="fa-solid fa-up-right-from-square"></i>
            </a>
        </div>
        <div class="project_panel" id="django_desc">
            <img src="/media/django-progress.png" alt="Web Portfolio Project">
            <div>
                <i class="fa-solid fa-check"></i><span>Landing Page</span>
            </div>
            <div>
                <i class="fa-solid fa-wrench"></i><span>Demais páginas</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>Integração com Twitch</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>Integração com Instagram</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>Integração com TikTok</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>Integração com For The Reign</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>Deploy</span>
            </div>
            <a href="https://github.com/SoldadoZuero/my_portfolio" class="project_button button_django" rel="noopener noreferrer" target="_blank">
                Open Code 
                <i class="fa-brands fa-github"></i>
            </a>
        </div>
        <div class="project_panel" id="ftr_desc">
            <img src="/media/For-the-Reign-Icon.png" alt="For the Reign Project">
            <div>
                <i class="fa-solid fa-check"></i><span>Modpack</span>
            </div>
            <div>
                <i class="fa-solid fa-check"></i><span>Lobby</span>
            </div>
            <div>
                <i class="fa-solid fa-check"></i><span>Servidor do Discord</span>
            </div>
            <div>
                <i class="fa-solid fa-check"></i><span>Trailer do servidor</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>Servidor de Hospedagem</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>Pagamento externo</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>Lançamento oficial</span>
            </div>
        </div>
        <div class="project_panel" id="js_desc">
            <img src="/media/icons8-javascript.svg" alt="JavaScript Project">
            <div>
                <i class="fa-solid fa-check"></i><span>Básico</span>
            </div>
            <div>
                <i class="fa-solid fa-check"></i><span>Lógica de programação</span>
            </div>
            <div>
                <i class="fa-solid fa-check"></i><span>P.O.O.</span>
            </div>
            <div>
                <i class="fa-solid fa-check"></i><span>Assíncrono</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>NodeJS</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>API REST</span>
            </div>
            <div>
                <i class="fa-regular fa-hourglass-half"></i><span>React</span>
            </div>
        </div>
        <div class="project_panel" id="other_projects">
            <img src="/media/logo.png" alt="SoldadoZuero Logo">
            <div>
                <span>
                    São diversos projetos em que trabalho, esses são apenas os principais,
                    aqui você pode verificar todos os outros e os detalhes sobre eles.
                </span>
            </div>
            <a href="{% url "principal:projects" %}" class="project_button button_project">
                Veja Mais
            </a>
        </div>
    </div>
</div>